#!/usr/bin/bash

args="${1---total}"

function pline() {
	printf "%-16s %-16s%4s %5s %5s %5s" "$1" "$2" "$3" "$4" "$5" "$6"
}

pline "Mount Point" "Device" "Size" "Used" "Free" "Use%"
echo ""

df -Hl -x fuse.ciopfs -x tmpfs -x devtmpfs \
		--output=target,source,pcent,size,used,avail "$args" | tail -n+2 \
		| tr -s ' ' | tr ' ' '\0' | sort | tr '\0' ' ' | while read -r line; do
	tar="$(echo "$line" | cut -d' ' -f1)"
	src="$(echo "$line" | cut -d' ' -f2)"
	perc="$(echo "$line" | cut -d' ' -f3)"
	size="$(echo "$line" | cut -d' ' -f4)"
	used="$(echo "$line" | cut -d' ' -f5)"
	avail="$(echo "$line" | cut -d' ' -f6)"
	pline "${tar}" "${src}" "${size}" "${used}" "${avail}" "${perc}"
	echo -n "  "
	usage_bar "$perc" 50
	echo ""
done

